

### GET ALL ENTRIES
GET https://localhost:7276/entries HTTP/1.1



### ADD NEW ENTRY
POST https://localhost:7276/entries HTTP/1.1
content-type: application/json

{
    "unitId": 2, "eventId": 3, "userId": 1, "measure": null, "tag": 3, "notes": null
}


### GET ALL UNITS
GET https://localhost:7276/units HTTP/1.1



### GET ALL EVENTS
GET https://localhost:7276/events HTTP/1.1



### GET ALL USERS
GET https://localhost:7276/users HTTP/1.1






### SIGN IN // demo@user.com:bananer, john@doe.com:eple, jane@doe.com:saft
POST https://localhost:7276/account/signin HTTP/1.1
content-type: application/json

{
    "email": "jane@doe.com", "password": "saft" 
}

